#!/bin/bash
source /etc/profile

cd $(dirname $0)

exec java -Xmx1024M -Xms512M -Djava.rmi.server.hostname=172.16.20.12 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9004 -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.authenticate=false  -cp conf:lib/* com.sauzny.blacksmith.provider.BlackSmithServerBoot
